name: APPS
on:
  workflow_dispatch:
    inputs:
      repo:
        description: repo
        required: true
        default: 'https://github.com/wxy1343/ManifestAutoUpdate'
    branches:
      - main
  schedule:
    - cron: '0 16 * * *'
concurrency:
  group: wait
  cancel-in-progress: false
jobs:
  apps:
    runs-on: windows-latest
    steps:
      - uses: actions/checkout@v3
        with:
          fetch-depth: 1
          submodules: recursive
      - name: Set up Python 3.10
        uses: actions/setup-python@v3
        with:
          python-version: "3.10"
      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt
      - run: |
          git config --local user.name github-actions[bot]
          git config --local user.email 41898282+github-actions[bot]@users.noreply.github.com
          python main.py -i -P -k ${{ secrets.KEY }}
          python apps.py -r ${{ github.event.inputs.repo || 'https://github.com/wxy1343/ManifestAutoUpdate' }} -o data
          python push.py