name: MERGE
on:
  workflow_dispatch:
    inputs:
      level:
        description: Logging Level
        required: true
        default: INFO
        type: choice
        options:
          - CRITICAL
          - FATAL
          - ERROR
          - WARNING
          - WARN
          - INFO
          - DEBUG
          - NOTSET
  schedule:
    - cron: '0 */8 * * *'
concurrency:
  group: wait
  cancel-in-progress: false
jobs:
  merge:
    runs-on: windows-latest
    steps:
      - uses: actions/checkout@v3
        with:
          fetch-depth: 1
          submodules: recursive
      - name: Set up Python 3.10
        uses: actions/setup-python@v3
        with:
          python-version: "3.10"
      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt
      - run: |
          git config --local user.name github-actions[bot]
          git config --local user.email 41898282+github-actions[bot]@users.noreply.github.com
          python main.py -i -P -k ${{ secrets.KEY }} -l ${{ github.event.inputs.level || 'INFO' }}
          python merge.py -t ${{ secrets.GITHUB_TOKEN }} -l ${{ github.event.inputs.level || 'INFO' }}
          python push.py